# Generated by Django 5.1.1 on 2024-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_alter_event_start_time'), ('events', '0003_alter_event_description_alter_event_name'), ('events', '0004_alter_event_end_time_alter_event_start_time'), ('events', '0005_alter_event_options'), ('events', '0006_event_is_registration_open'), ('events', '0007_event_hidden')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('is_registration_open', models.BooleanField(default=True, help_text='Внимание. Регистрация автоматически закрывается при открытии мероприятия', verbose_name='Регистрация')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыть мероприятие')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
