# Generated by Django 5.1.1 on 2024-09-08 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('send_push', models.BooleanField(default=False, help_text='Для скрытых мероприятий push уведомления отключены', verbose_name='Отправить push')),
                ('is_registration_open', models.BooleanField(default=True, help_text='Внимание. Регистрация автоматически закрывается при открытии мероприятия', verbose_name='Регистрация')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыть мероприятие')),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
