# Generated by Django 5.1.1 on 2024-09-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_push',
            field=models.BooleanField(default=False, help_text='При создании. Для всех тех, кто подписан на уведомления.', verbose_name='Отправить push'),
        ),
    ]
