# Generated by Django 5.1.1 on 2024-09-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_send_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='send_push',
            field=models.BooleanField(default=False, verbose_name='Отправить push'),
        ),
    ]
