# Generated by Django 5.1.1 on 2024-09-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrewardcouter',
            options={'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчики'},
        ),
    ]
