# Generated by Django 5.1.1 on 2024-09-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0004_userachievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
