# Generated by Django 5.1.1 on 2024-09-07 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=256, verbose_name='Авторство')),
                ('certificate_number', models.CharField(help_text='Номер состоит из 20 символов', max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(20)], verbose_name='№ сертификата')),
                ('certification_year', models.SmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Год сертификации')),
                ('number_of_printed_pages', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Количество печатных страниц')),
                ('number_of_images', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Количество рисунков')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
