# Generated by Django 5.1.1 on 2024-09-07 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='certificate_number',
            field=models.CharField(help_text='Номер состоит из 8 символов', max_length=8, unique=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)], verbose_name='№ сертификата'),
        ),
    ]
