# Generated by Django 5.1.1 on 2024-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_count_bookdebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='Количество книжних копий в наличии', verbose_name='Наличие (шт)'),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='date_of_deadline',
            field=models.DateField(verbose_name='Время возврата'),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, verbose_name='Время выдачи'),
        ),
    ]
