# Generated by Django 5.1.1 on 2024-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_count_alter_bookdebt_date_of_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdebt',
            name='date_of_deadline',
            field=models.DateField(verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
    ]
