# Generated by Django 5.1.1 on 2024-09-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_count_alter_bookdebt_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdebt',
            options={'verbose_name': 'выдачу', 'verbose_name_plural': 'выдача'},
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='count',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Количество выдаваемых экземпляров', verbose_name='Экземпляров'),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
    ]
