# Generated by Django 5.1.1 on 2024-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookdebt_options_alter_bookdebt_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdebt',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Количество выдаваемых экземпляров', verbose_name='Экземпляров'),
        ),
    ]
