# Generated by Django 5.1.1 on 2024-09-07 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookdebt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdebt',
            name='_count_dump',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bookdebt',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Количество выдаваемых экземпляров', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Экземпляров'),
        ),
    ]
